/*
 * fillp_frame.h - fillp (Dstream) packet codec
 *
 * Wire format from the public OpenHarmony fillp source
 * (communication_t2stack/fillp/src/fillp_lib, fillp.h / fillp_cookie.h),
 * cross-checked against the t2stack fillp RE notes (spec §8).
 *
 * fillp is a reliable, ordered byte stream over UDP (mini-TCP): one
 * fillp "connection" is bidirectional, each endpoint keeps its own send
 * counters (pktNum 1-based, seqNum cumulative byte offset) and its own
 * receive counters. Reliability: cumulative ack via PACK, loss recovery
 * via NACK (retransmission of the first gap).
 *
 * Datagram = 12-byte head + payload, all integers big-endian.
 *
 *   Head (FILLP_HLEN = 12):
 *     u16 flag     [15:12] protocol version (0)
 *                  [11:8]  packet type (FpPktType)
 *                  [7]     DATA-with-option  (0x80, options after payload)
 *                  [6]     DATA last-of-burst (0x40)
 *                  [5]     DATA first-of-burst (0x20)
 *     u16 dataLen  payload length in bytes
 *     u32 pktNum   sender's DATA packet number (1-based, mgmt = 0)
 *     u32 seqNum   sender's cumulative byte offset INCLUDING this
 *                  DATA packet's payload (mgmt: 0)
 *
 *   Management payloads (packed, BE):
 *     CONN_REQ       (20B): u32 cookiePreserveTime, u32 sendCache,
 *                           u32 recvCache, u64 timestamp
 *     CONN_REQ_ACK   (120B): u16 tagCookie, u16 cookieLength (=108),
 *                            cookie[108], u64 timestamp
 *     CONN_CONFIRM   (140B): u16 tagCookie, u16 cookieLength (=108),
 *                            cookie[108], addr[28] (client local addr;
 *                            "kept for backward compatibility" upstream)
 *     CONN_CONFIRM_ACK (40B): u32 sendCache, u32 recvCache, u32 pktSize,
 *                            addr[28] (server local addr)
 *     NACK / HISTORY_NACK (12B): u32 lastPktNum, u64 randomNum
 *     PACK           (46B payload, 58B with head): u16 flag, u16 pktLoss,
 *                                   u32 rate, u32 oppositeSetRate, u32 lostSeq,
 *                                   u32 reserved, u32 bgnPktNum,
 *                                   u32 endPktNum, u16 optsOffset,
 *                                   u32 rcvListBytes, u32 owdPktSendTs,
 *                                   u32 owdPackDelay, u32 queueingDelay
 *     The real stack sizes PACK by flag bits (32/40/42/46/58B total:
 *     FILLP_PACK_MIN_LEN ... FILLP_PACK_OWD_LEN); the stand always sends
 *     the full OWD variant.
 *     FIN            (2B): u16 flag
 *
 *   Cookie (FILLP_COOKIE_LEN = 108B, packed, BE) — generated by the
 *   fillp SERVER on CONN_REQ, verified on CONN_CONFIRM:
 *     digest[32]  HMAC-SHA256 digest (see fillp_cookie_fill/verify)
 *     arr[16]     generation timestamp (u64, µs, in the first 8 bytes)
 *     u32 lifeTime, u32 localPacketSeqNumber, u32 remotePacketSeqNumber,
 *     u32 localMessageSeqNumber, u32 remoteMessageSeqNumber,
 *     u32 remoteSendCache, u32 remoteRecvCache,
 *     u16 srcPort, u16 addressType, remoteSock[28]
 *
 *   The HMAC key is a local 32-byte "MAC key" of the server (random,
 *   never sent over the wire — DTLS-style). HMAC input = cookie[32..108)
 *   || localAddr[28] (104 bytes).
 *
 *   28-byte address field ("sockaddr_in6 compat"): upstream memcpy's
 *   sizeof(struct sockaddr_in) = 16 bytes for AF_INET, the rest is zero.
 *   fillp_addr_fill_ipv4() reproduces that layout.
 *
 * Replay-stand conventions (spec §8.7): stand NACK carries
 * {head.pktNum = last in-order, payload.lastPktNum = last in-order + 2,
 * head.seqNum = recv byte offset} so the sender retransmits exactly the
 * first missing packet; stand PACK carries cumulative ack in
 * {head.seqNum, head.pktNum, lostSeq = head.seqNum}.
 */

#pragma once

#include <glib.h>

G_BEGIN_DECLS

#define FILLP_HLEN        12
#define FILLP_COOKIE_LEN  108
#define FILLP_ADDR_LEN    28

#define FILLP_FLAG_DATA_OPT   0x80 /* options after DATA payload      */
#define FILLP_FLAG_DATA_LAST  0x40 /* DATA: last of a large burst     */
#define FILLP_FLAG_DATA_FIRST 0x20 /* DATA: first of a large burst    */

typedef enum {
  FP_PKT_DATA             = 0x1,
  FP_PKT_CONN_REQ         = 0x2,
  FP_PKT_NACK             = 0x3,
  FP_PKT_PACK             = 0x5,
  FP_PKT_FIN              = 0x6,
  FP_PKT_CONN_REQ_ACK     = 0xA,
  FP_PKT_CONN_CONFIRM     = 0xB,
  FP_PKT_CONN_CONFIRM_ACK = 0xC,
  FP_PKT_HISTORY_NACK     = 0xD,
} FpPktType;

/* Payload sizes (bytes, without the 12B head). */
#define FILLP_CONN_REQ_LEN       20
#define FILLP_CONN_REQ_ACK_LEN   120
#define FILLP_CONN_CONFIRM_LEN   140
#define FILLP_CONN_CONFIRM_ACK_LEN 40
#define FILLP_NACK_LEN           12
#define FILLP_PACK_LEN           46
#define FILLP_FIN_LEN            2

/* ============================ Head ============================ */

/*
 * Encode the 12-byte head into @buf (must be >= FILLP_HLEN).
 * @type is an FpPktType; @extra ORs in DATA_FIRST/LAST/OPT flags.
 * Returns FILLP_HLEN.
 */
gsize fillp_encode_head(guint8 *buf, FpPktType type, guint16 extra,
                        guint16 data_len, guint32 pkt_num, guint32 seq_num);

/*
 * Decode the 12-byte head from @buf/@len. Version must be 0.
 * @type_out / @flags_out / @data_len_out / @pkt_num_out / @seq_num_out
 * may be NULL to skip a field. Returns FALSE on short buffer or
 * unknown version.
 */
gboolean fillp_decode_head(const guint8 *buf, gsize len, FpPktType *type_out,
                           guint16 *flags_out, guint16 *data_len_out,
                           guint32 *pkt_num_out, guint32 *seq_num_out);

/* Wraparound-safe signed comparison: TRUE if @a is "ahead of" @b. */
gboolean fp_num_isbigger(guint32 a, guint32 b);

/* ============================ Management ============================ */

/*
 * Encoders: write the full datagram (head + payload) into @buf/@cap and
 * return the total length, or -1 when @cap is too small.
 * Decoders: @buf/@len is the full datagram; return FALSE on size mismatch
 * (the head must already have been decoded / type-checked by the caller).
 */
gssize fillp_encode_conn_req(guint8 *buf, gsize cap,
                             guint32 cookie_preserve_time_us,
                             guint32 send_cache, guint32 recv_cache,
                             guint64 timestamp_us);
gboolean fillp_decode_conn_req(const guint8 *buf, gsize len,
                               guint32 *cookie_preserve_time_us,
                               guint32 *send_cache, guint32 *recv_cache,
                               guint64 *timestamp_us);

gssize fillp_encode_conn_req_ack(guint8 *buf, gsize cap, guint16 tag_cookie,
                                 const guint8 cookie[FILLP_COOKIE_LEN],
                                 guint64 timestamp_us);
gboolean fillp_decode_conn_req_ack(const guint8 *buf, gsize len,
                                   guint16 *tag_cookie,
                                   guint8 cookie_out[FILLP_COOKIE_LEN],
                                   guint64 *timestamp_us);

gssize fillp_encode_conn_confirm(guint8 *buf, gsize cap, guint16 tag_cookie,
                                 const guint8 cookie[FILLP_COOKIE_LEN],
                                 const guint8 local_addr[FILLP_ADDR_LEN]);
gboolean fillp_decode_conn_confirm(const guint8 *buf, gsize len,
                                   guint16 *tag_cookie,
                                   guint8 cookie_out[FILLP_COOKIE_LEN],
                                   guint8 local_addr_out[FILLP_ADDR_LEN]);

gssize fillp_encode_conn_confirm_ack(guint8 *buf, gsize cap,
                                     guint32 send_cache, guint32 recv_cache,
                                     guint32 pkt_size,
                                     const guint8 local_addr[FILLP_ADDR_LEN]);
gboolean fillp_decode_conn_confirm_ack(const guint8 *buf, gsize len,
                                       guint32 *send_cache,
                                       guint32 *recv_cache,
                                       guint32 *pkt_size,
                                       guint8 local_addr_out[FILLP_ADDR_LEN]);

/*
 * NACK: head.pktNum = @begin_pkt (last known in-order), head.seqNum =
 * @seq_num (recv byte offset), payload lastPktNum = @end_pkt - 1, i.e.
 * "retransmit (begin, end)". @random_num defeats firewall dedup.
 */
gssize fillp_encode_nack(guint8 *buf, gsize cap, FpPktType type,
                         guint32 begin_pkt, guint32 end_pkt, guint32 seq_num,
                         guint64 random_num);
gboolean fillp_decode_nack(const guint8 *buf, gsize len, guint32 *begin_pkt,
                           guint32 *end_pkt, guint32 *seq_num);

/*
 * PACK: cumulative ack — head.pktNum = @ack_pkt (last in-order),
 * head.seqNum = @ack_seq (first not-acked byte), lostSeq = @lost_seq
 * (== ack_seq when no loss), rcvListBytes = out-of-order buffered bytes.
 */
gssize fillp_encode_pack(guint8 *buf, gsize cap, guint32 ack_seq,
                         guint32 ack_pkt, guint32 lost_seq,
                         guint32 rcv_list_bytes);
gboolean fillp_decode_pack(const guint8 *buf, gsize len, guint32 *ack_seq,
                           guint32 *ack_pkt, guint32 *lost_seq,
                           guint32 *rcv_list_bytes);

gssize fillp_encode_fin(guint8 *buf, gsize cap, guint16 flag);
gboolean fillp_decode_fin(const guint8 *buf, gsize len, guint16 *flag);

/* ============================ Cookie ============================ */

/*
 * Build a 108-byte cookie and compute its digest (see header doc for the
 * HMAC input). @mac_key is the local 32-byte key (never sent).
 * @local_addr / @remote_addr are 28-byte compat address fields.
 */
void fillp_cookie_fill(guint8 cookie[FILLP_COOKIE_LEN],
                       const guint8 mac_key[32], guint64 gen_time_us,
                       guint32 life_time_us, guint32 local_pkt_seq,
                       guint32 local_msg_seq, guint32 remote_pkt_seq,
                       guint32 remote_msg_seq, guint32 remote_send_cache,
                       guint32 remote_recv_cache, guint16 src_port,
                       guint16 addr_type,
                       const guint8 remote_addr[FILLP_ADDR_LEN],
                       const guint8 local_addr[FILLP_ADDR_LEN]);

/* Recompute the digest and compare (constant-time). */
gboolean fillp_cookie_verify(const guint8 cookie[FILLP_COOKIE_LEN],
                             const guint8 mac_key[32],
                             const guint8 local_addr[FILLP_ADDR_LEN]);

/*
 * Fill a 28-byte compat address from an IPv4 address: u16 family,
 * u16 port (BE), 4B IPv4, 12B zero (the 16-byte sockaddr_in layout
 * memcpy'd into the 28-byte field, as upstream does for AF_INET).
 */
void fillp_addr_fill_ipv4(guint8 addr[FILLP_ADDR_LEN], guint16 port,
                          const guint8 ipv4[4]);

G_END_DECLS
